version: '3.8'

services:
  frontend:
    image: registry.cn-hongkong.aliyuncs.com/velero/xxj-nginx:2025122921
    container_name: xiuxian-frontend
    ports:
      - "315:315"
    networks:
      - xiuxian-network
    depends_on:
      - backend

  backend:
    image: registry.cn-hongkong.aliyuncs.com/velero/xxj-server:2025122921
    container_name: xiuxian-backend
    ports:
      - "3000:3000"
    env_file:
    - .env
    networks:
      - xiuxian-network

networks:
  xiuxian-network:
    driver: bridge